[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
bounty_platform = "CZvJ2JhfjYGvwUYzbaVj8JiydgEo82wKMvkx4fNurvq2"

[programs.localnet]
bounty_platform = "J1joaPPEAzELE9jSLZajxZyAe6hrMAsMkQUjFJLLQK7P"

[programs.testnet]
bounty_platform = "J1joaPPEAzELE9jSLZajxZyAe6hrMAsMkQUjFJLLQK7P"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

# Add this section for a faster RPC
[provider.devnet]
url='https://devnet.helius-rpc.com/?api-key=d9b9a17e-14dc-4e55-996f-02e096dc0c53'
[scripts]
test = "npx ts-mocha tests/**/*.ts --exit --timeout 30000"

[hooks]
