[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
bounty_platform = "CZvJ2JhfjYGvwUYzbaVj8JiydgEo82wKMvkx4fNurvq2"

[programs.localnet]
bounty_platform = "J1joaPPEAzELE9jSLZajxZyAe6hrMAsMkQUjFJLLQK7P"

[programs.testnet]
bounty_platform = "J1joaPPEAzELE9jSLZajxZyAe6hrMAsMkQUjFJLLQK7P"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha tests/**/*.ts --exit --timeout 30000"

[hooks]
